---
title: "data_manipulation"
author: "DZ"
date: "September 18, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(skimr)
```

## Import FAS data

Import my first csv

```{r}
litter_data <- read_csv(file = './data/FAS_litters.csv',col_types = 'ccddiiii')
litter_data <- janitor::clean_names(litter_data)
pups_data <- read_csv(file='./data/FAS_pups.csv', col_types = 'ciiiii')
pups_data <- janitor::clean_names(pups_data)


```

## Select Variables
```{r}
select(litter_data, litter_number, gd0_weight)
select(litter_data, litter_number, gd0_weight)

select(litter_data, group, gd_of_birth:pups_survive)
select(litter_data, -litter_number)




```

### rename
```{r}
select(litter_data, litter_number, gd0_day_0_weight=gd0_weight)
rename(litter_data,  gd0_day_0_weight=gd0_weight)
```

... use select helpers
```{r}
select(litter_data, starts_with('gd'))
select(litter_data, litter_number, starts_with('pup'))
select(litter_data, litter_number, everything())
```

head(pups_data)

### exercise

```{r}
select(pups_data,  litter_number, sex, pd_ears)
```


### Filter
```{r}
filter(litter_data, gd0_weight < 25)
filter(litter_data, gd0_weight >= 25)

filter(litter_data, pups_born_alive == 8)

filter( litter_data, is.na(gd0_weight))
filter( litter_data, !is.na(gd0_weight))

filter(litter_data, group =='Low8' | group=='Low7')
filter(litter_data, group %in% c('Low7', 'Low8'))

filter(litter_data, pups_born_alive %in% 4:6,  !is.na(gd0_weight))

filter(pups_data, sex== 1)
filter(pups_data, pd_walk<11, sex==2)

```


### Mutate
create variables
```{r}
mutate(litter_data, 
       wt_gain = gd18_weight-gd0_weight,
       group = tolower(group))

mutate(litter_data, 
       wt_gain = gd18_weight-gd0_weight,
       wt_gain_squared = wt_gain)
```

### Arange

```{r}
arrange(litter_data, gd0_weight)

arrange(litter_data, pups_born_alive, gd0_weight)

```


Pipeline

```{r}
read_csv(file = './data/FAS_litters.csv', col_types = 'ccddiiii') %>% 
  janitor::clean_names() %>% 
  select(-pups_born_alive) %>% 
  mutate(
      wt_gain = gd18_weight - gd0_weight,
      group = tolower(group)) %>% 
  filter(!is.na(gd0_weight)) %>% 
  lm(gd18_weight~gd0_weight, data=.)



```

