---
title: "EDA"
author: "DZ"
date: "October 4, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_bw() + theme(legend.position = "bottom"))
```

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, date, month, everything())

```

### Group_by
```{r}
weather_df %>% 
  group_by(name,month) %>% 
  summarise(number=n())

weather_df %>% 
  group_by(name,month) %>% 
  summarize(n_obs = n(),
            n_days = n_distinct(date))

weather_df %>% 
  count(month,name)

weather_df %>% 
  group_by(name) %>% 
  summarise(number=n())
```

Tidy is not always the best for humans...
```{r}
weather_df %>%
  group_by(name, month) %>%
  summarize(mean_tmax = mean(tmax)) %>%
  spread(key=name, value=mean_tmax) %>% 
  knitr::kable(digits = 1)
```

