---
title: "Reading tables from the web"
author: "DZ"
date: "October 11, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(tidyverse)
library(httr)
```

Scraping
```{r}
url <- "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_xml = read_html(url)

drug_use_xml %>%
  html_nodes(css = "table") %>% 
  .[[1]] %>%
  html_table() %>% 
  slice(-1) %>% 
  as.tibble()
```

Exercise
```{r}
url_haha <- 'https://www.bestplaces.net/cost_of_living/city/new_york/new_york'

df_xml <- read_html(url_haha)

df_xml %>% 
  html_nodes(css='table') %>% 
  .[[1]] %>% 
  html_table(header = T)

nyc_cost = read_html("https://www.bestplaces.net/cost_of_living/city/new_york/new_york") %>%
  html_nodes(css = "table") %>%
  .[[1]] %>%
  html_table(header = TRUE)
```

Harry Potter
```{r}
harrypotter <- read_html("https://www.imdb.com/list/ls000630791/") %>% 
  html_nodes(css = '.lister-item-header a') %>% 
  html_text()
```


## API

Get the water data
```{r}
water <- GET('https://data.cityofnewyork.us/resource/waf7-5gvc.json') %>% 
  content('parse')
```

