---
title: "data_manipulation"
author: "DZ"
date: "September 25, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(skimr)
```

## Import Pulse data

Import my first csv

```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data

pulse_tidy <- pulse_data %>% 
  gather(key='visit', value='bdi', bdi_score_bl:bdi_score_12m)
```

## Separate
```{r}
pulse_tidy %>% 
  separate(visit, into = c('bdi_str','score_str','visit'), sep = '_') %>% 
  select(-bdi_str,-score_str) %>% 
  mutate(visit=replace(visit, visit=='bl','00m'))
```

## All Together
```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names()
pulse_data

pulse_tidy <- pulse_data %>% 
  gather(key='visit', value='bdi', bdi_score_bl:bdi_score_12m)

pulse_clean <- pulse_tidy %>% 
  separate(visit, into = c('bdi_str','score_str','visit'), sep = '_') %>% 
  select(-bdi_str,-score_str) %>% 
  mutate(visit=replace(visit, visit=='bl','00m'))
```

## Revisit FAS_litters
```{r}
litter_data <- read_csv(file = './data/FAS_litters.csv',col_types = 'ccddiiii') %>% 
janitor::clean_names() %>% 
  separate(group, into=c('dose','day'),sep = 3) 

litter_data <- read_csv(file = './data/FAS_litters.csv',col_types = 'ccddiiii') %>% 
  janitor::clean_names() %>% 
  select( ends_with('weight')) %>% 
  gather(key='gd', value='weight', gd0_weight:gd18_weight) %>% 
  mutate(gd = recode(gd, "gd0_weight" = 0, "gd18_weight" = 18))

```


## Spread
```{r}
analysis_result = tibble(
  group = c("treatment", "treatment", "placebo", "placebo"),
  time = c("pre", "post", "pre", "post"),
  mean = c(4, 8, 3.5, 4)
)

analysis_result %>% 
  spread(key = time,value=mean) %>% 
  knitr::kable()

```

## bind Datasets
```{r}
fellowship_ring = readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") %>%
  mutate(movie = "fellowship_ring")

two_towers = readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") %>%
  mutate(movie = "two_towers")

return_king = readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") %>%
  mutate(movie = "return_king")

### Create final data
bind_rows(fellowship_ring, two_towers, return_king) %>% 
  janitor::clean_names() %>% 
  gather(key='sex', value=word, female:male) %>% 
  mutate(race= tolower(race))

```

## Join data
```{r}
pup_data = read_csv("./data/FAS_pups.csv", col_types = "ciiiii") %>%
  janitor::clean_names() %>%
  mutate(sex = recode(sex, `1` = "male", `2` = "female")) 

litter_data = read_csv("./data/FAS_litters.csv", col_types = "ccddiiii") %>%
  janitor::clean_names() %>%
  select(-pups_survive) %>%
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = tolower(group))
FAS_data = left_join(pup_data, litter_data, by = "litter_number")
FAS_data
```

